services:
  server:
    image: multithreading-demo
    build: .
    ports:
      - "8080:80"
      # - "8443:443"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MultithreadingContext=Data Source=/multithreading-demo/data/Multithreading.db
    volumes:
      - db:/multithreading-demo/data
volumes:
  db: