
CREATE TABLE demo (
    id integer NOT NULL PRIMARY KEY,
    title varchar(255) NOT NULL,
    author_id varchar(40) NOT NULL, -- ASP.NET core identity users table uses guid strings for id.
    visibility smallint NOT NULL CHECK (visibility IN (0, 1)), -- 0 is private, 1 is public.
    description text DEFAULT "",
    created_at datetime NOT NULL,
    updated_at datetime NOT NULL,
    FOREIGN KEY (author_id) REFERENCES AspNetUsers(Id) ON DELETE CASCADE
);

CREATE TABLE thread (
    id integer NOT NULL PRIMARY KEY,
    demo_id integer NOT NULL,
    pos integer NOT NULL CHECK (pos >= 0),
    code text NOT NULL,
	UNIQUE (demo_id, pos),
    FOREIGN KEY (demo_id) REFERENCES demo(id) ON DELETE CASCADE
);

CREATE TABLE playback (
    id integer NOT NULL PRIMARY KEY,
    demo_id integer NOT NULL,
    name varchar(255) NOT NULL,
    FOREIGN KEY (demo_id) REFERENCES demo(id) ON DELETE CASCADE
);

CREATE TABLE step (
    id integer NOT NULL PRIMARY KEY,
    playback_id integer NOT NULL,
    thread_pos integer NOT NULL CHECK (thread_pos >= 0),
    wake_thread_pos integer CHECK (wake_thread_pos >= 0),
    pos integer NOT NULL CHECK (pos >= 0),
    breakpoint smallint NOT NULL CHECK (breakpoint IN (0, 1)),
    FOREIGN KEY (playback_id) REFERENCES playback(id) ON DELETE CASCADE
);

CREATE TABLE demo_tag (
    demo_id integer NOT NULL,
    tag_name varchar(255) NOT NULL,
    PRIMARY KEY (demo_id,tag_name),
    FOREIGN KEY (demo_id) REFERENCES demo(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_name) REFERENCES tag(name) ON DELETE CASCADE
);

CREATE TABLE tag (
    name varchar(255) NOT NULL PRIMARY KEY
);

-- User Table generated by ASP.NET Core Identity. Relevant portions of the schema for the table are:
-- CREATE TABLE AspNetUsers (
--     Id TEXT NOT NULL CONSTRAINT "PK_AspNetUsers" PRIMARY KEY, -- A guid.
--     UserName TEXT NULL,
--     PasswordHash TEXT NULL
-- );

-- Populate Tags
INSERT INTO tag(name) VALUES
    ("Mutexes"), ("Condition Variables"), ("Semaphores"), ("Race Conditions"), ("Deadlock")